import { Province, FeaturedAttraction, Shop } from './types';
import { provinceImages, attractionImages, shopImages } from './image_assets';
import { INITIAL_SHOPS } from './marketplace_config';

// Export LOCAL_SHOPS so it can be used by the ItineraryPlanner
export const LOCAL_SHOPS: Shop[] = INITIAL_SHOPS;

export const PROVINCES: Province[] = [
  // Central
  { name: 'Bangkok', description: 'The vibrant capital, a city of contrasts with action at every turn.', imageUrl: provinceImages.Bangkok, region: 'Central', lat: 13.7563, lng: 100.5018 },
  { name: 'Ayutthaya', description: 'The former capital, rich in history with impressive ancient ruins.', imageUrl: provinceImages.Ayutthaya, region: 'Central', lat: 14.3524, lng: 100.5694 },
  { name: 'Ang Thong', description: 'Known for its handicrafts and the large reclining Buddha at Wat Pa Mok.', imageUrl: provinceImages['Ang Thong'], region: 'Central', lat: 14.588, lng: 100.4552 },
  { name: 'Chai Nat', description: 'A peaceful province on the Chao Phraya River basin, known for its large bird park.', imageUrl: provinceImages['Chai Nat'], region: 'Central', lat: 15.1856, lng: 100.1264 },
  { name: 'Lopburi', description: 'Famous for its ancient Khmer temples and the hordes of monkeys that roam the city.', imageUrl: provinceImages.Lopburi, region: 'Central', lat: 14.7983, lng: 100.6533 },
  { name: 'Nakhon Nayok', description: 'A gateway to Khao Yai National Park, offering waterfalls and nature.', imageUrl: provinceImages['Nakhon Nayok'], region: 'Central', lat: 14.2072, lng: 101.2131 },
  { name: 'Nakhon Pathom', description: 'Home to the giant Phra Pathom Chedi, the tallest stupa in the world.', imageUrl: provinceImages['Nakhon Pathom'], region: 'Central', lat: 13.818, lng: 100.062 },
  { name: 'Nonthaburi', description: 'A bustling province bordering Bangkok, known for its floating markets.', imageUrl: provinceImages.Nonthaburi, region: 'Central', lat: 13.861, lng: 100.518 },
  { name: 'Pathum Thani', description: 'An important center for education and research, with many universities.', imageUrl: provinceImages['Pathum Thani'], region: 'Central', lat: 14.020, lng: 100.531 },
  { name: 'Samut Prakan', description: 'Features the Erawan Museum and the impressive Ancient City outdoor museum.', imageUrl: provinceImages['Samut Prakan'], region: 'Central', lat: 13.599, lng: 100.597 },
  { name: 'Samut Sakhon', description: 'A major fishing port known for its abundance of fresh seafood.', imageUrl: provinceImages['Samut Sakhon'], region: 'Central', lat: 13.548, lng: 100.276 },
  { name: 'Samut Songkhram', description: 'Famous for the Maeklong Railway Market and Amphawa Floating Market.', imageUrl: provinceImages['Samut Songkhram'], region: 'Central', lat: 13.414, lng: 100.002 },
  { name: 'Saraburi', description: 'Known for its beautiful national parks and the revered Wat Phra Phutthabat.', imageUrl: provinceImages.Saraburi, region: 'Central', lat: 14.530, lng: 100.910 },
  { name: 'Sing Buri', description: 'A historic province known for its brave villagers who fought against Burmese invaders.', imageUrl: provinceImages['Sing Buri'], region: 'Central', lat: 14.891, lng: 100.404 },
  { name: 'Suphan Buri', description: 'A province with a long history, mentioned in ancient Thai legends.', imageUrl: provinceImages['Suphan Buri'], region: 'Central', lat: 14.471, lng: 100.119 },

  // North
  { name: 'Chiang Mai', description: 'The northern hub of culture, temples, and lush mountains.', imageUrl: provinceImages['Chiang Mai'], region: 'North', lat: 18.7883, lng: 98.9853 },
  { name: 'Chiang Rai', description: 'The gateway to the Golden Triangle, with the stunning White Temple.', imageUrl: provinceImages['Chiang Rai'], region: 'North', lat: 19.9095, lng: 99.8325 },
  { name: 'Kamphaeng Phet', description: 'Home to a UNESCO World Heritage historical park with ancient ruins.', imageUrl: provinceImages['Kamphaeng Phet'], region: 'North', lat: 16.483, lng: 99.522 },
  { name: 'Lampang', description: 'A charming city known for its horse-drawn carriages and unique temples.', imageUrl: provinceImages.Lampang, region: 'North', lat: 18.291, lng: 99.493 },
  { name: 'Lamphun', description: 'One of Thailand\'s oldest cities, with a rich history and beautiful temples.', imageUrl: provinceImages.Lamphun, region: 'North', lat: 18.577, lng: 99.009 },
  { name: 'Mae Hong Son', description: 'A mountainous province known for its mist-shrouded valleys and unique culture.', imageUrl: provinceImages['Mae Hong Son'], region: 'North', lat: 19.302, lng: 97.965 },
  { name: 'Nakhon Sawan', description: 'The "Heavenly City" where four major rivers converge.', imageUrl: provinceImages['Nakhon Sawan'], region: 'North', lat: 15.698, lng: 100.124 },
  { name: 'Nan', description: 'A quiet and remote province with stunning scenery and a slow pace of life.', imageUrl: provinceImages.Nan, region: 'North', lat: 18.777, lng: 100.779 },
  { name: 'Phayao', description: 'Known for the large and beautiful Kwan Phayao lake.', imageUrl: provinceImages.Phayao, region: 'North', lat: 19.163, lng: 99.904 },
  { name: 'Phetchabun', description: 'Features dramatic mountain scenery and cool climates.', imageUrl: provinceImages.Phetchabun, region: 'North', lat: 16.417, lng: 101.157 },
  { name: 'Phichit', description: 'The "Land of Crocodiles," with a rich history in Thai folklore.', imageUrl: provinceImages.Phichit, region: 'North', lat: 16.444, lng: 100.349 },
  { name: 'Phitsanulok', description: 'Home to the famous Phra Phuttha Chinnarat, one of Thailand\'s most beautiful Buddha images.', imageUrl: provinceImages.Phitsanulok, region: 'North', lat: 16.822, lng: 100.259 },
  { name: 'Phrae', description: 'A city with a rich Lanna heritage and many traditional teakwood houses.', imageUrl: provinceImages.Phrae, region: 'North', lat: 18.144, lng: 100.139 },
  { name: 'Sukhothai', description: 'The birthplace of the Thai nation, with a stunning historical park.', imageUrl: provinceImages.Sukhothai, region: 'North', lat: 17.009, lng: 99.824 },
  { name: 'Tak', description: 'A mountainous province bordering Myanmar, known for its trekking and nature.', imageUrl: provinceImages.Tak, region: 'North', lat: 16.861, lng: 99.125 },
  { name: 'Uthai Thani', description: 'A tranquil province known for its floating houses and natural beauty.', imageUrl: provinceImages['Uthai Thani'], region: 'North', lat: 15.378, lng: 100.027 },
  { name: 'Uttaradit', description: 'The "Port of the North," known for its delicious durian and long-history.', imageUrl: provinceImages.Uttaradit, region: 'North', lat: 17.625, lng: 100.093 },
  
  // Northeast (Isan)
  { name: 'Amnat Charoen', description: 'A peaceful province known for its Buddhist amulets.', imageUrl: provinceImages['Amnat Charoen'], region: 'Northeast', lat: 15.860, lng: 104.629 },
  { name: 'Bueng Kan', description: 'Thailand\'s newest province, with stunning Mekong River scenery.', imageUrl: provinceImages['Bueng Kan'], region: 'Northeast', lat: 18.361, lng: 103.652 },
  { name: 'Buriram', description: 'A province famous for its ancient Khmer ruins and modern international racing circuit.', imageUrl: provinceImages.Buriram, region: 'Northeast', lat: 14.995, lng: 103.102 },
  { name: 'Chaiyaphum', description: 'Known for its fields of Siamese tulips and beautiful national parks.', imageUrl: provinceImages.Chaiyaphum, region: 'Northeast', lat: 15.807, lng: 102.031 },
  { name: 'Kalasin', description: 'A major center for dinosaur fossils in Thailand.', imageUrl: provinceImages.Kalasin, region: 'Northeast', lat: 16.432, lng: 103.504 },
  { name: 'Khon Kaen', description: 'One of the major cities in Isan, known for its silk production.', imageUrl: provinceImages['Khon Kaen'], region: 'Northeast', lat: 16.447, lng: 102.833 },
  { name: 'Loei', description: 'A mountainous province with a cool climate, often called the "Switzerland of Thailand."', imageUrl: provinceImages.Loei, region: 'Northeast', lat: 17.486, lng: 101.729 },
  { name: 'Maha Sarakham', description: 'A center for education in the Isan region.', imageUrl: provinceImages['Maha Sarakham'], region: 'Northeast', lat: 16.182, lng: 103.303 },
  { name: 'Mukdahan', description: 'A province bordering Laos, known for the Ho Kaeo tower with panoramic views.', imageUrl: provinceImages.Mukdahan, region: 'Northeast', lat: 16.545, lng: 104.723 },
  { name: 'Nakhon Phanom', description: 'A charming province on the banks of the Mekong River.', imageUrl: provinceImages['Nakhon Phanom'], region: 'Northeast', lat: 17.407, lng: 104.781 },
  { name: 'Nakhon Ratchasima (Korat)', description: 'The largest province in Thailand and a gateway to the Isan region.', imageUrl: provinceImages['Nakhon Ratchasima (Korat)'], region: 'Northeast', lat: 14.972, lng: 102.099 },
  { name: 'Nong Bua Lamphu', description: 'A small province known for its archaeological sites.', imageUrl: provinceImages['Nong Bua Lamphu'], region: 'Northeast', lat: 17.207, lng: 102.443 },
  { name: 'Nong Khai', description: 'Famous for the mysterious Naga fireballs on the Mekong River.', imageUrl: provinceImages['Nong Khai'], region: 'Northeast', lat: 17.881, lng: 102.742 },
  { name: 'Roi Et', description: 'Known for its 101-meter-tall standing Buddha image.', imageUrl: provinceImages['Roi Et'], region: 'Northeast', lat: 16.054, lng: 103.652 },
  { name: 'Sakon Nakhon', description: 'A province with a rich history and strong Buddhist traditions.', imageUrl: provinceImages['Sakon Nakhon'], region: 'Northeast', lat: 17.159, lng: 104.148 },
  { name: 'Sisaket', description: 'Home to the stunning Preah Vihear sanctuary on the Cambodian border.', imageUrl: provinceImages.Sisaket, region: 'Northeast', lat: 15.119, lng: 104.323 },
  { name: 'Surin', description: 'Famous for its annual Elephant Round-up festival.', imageUrl: provinceImages.Surin, region: 'Northeast', lat: 14.883, lng: 103.493 },
  { name: 'Ubon Ratchathani', description: 'Known for its beautiful Candle Festival and stunning national parks.', imageUrl: provinceImages['Ubon Ratchathani'], region: 'Northeast', lat: 15.231, lng: 104.856 },
  { name: 'Udon Thani', description: 'A major commercial center and home to the Ban Chiang archaeological site.', imageUrl: provinceImages['Udon Thani'], region: 'Northeast', lat: 17.414, lng: 102.791 },
  { name: 'Yasothon', description: 'Famous for its spectacular Rocket Festival.', imageUrl: provinceImages.Yasothon, region: 'Northeast', lat: 15.794, lng: 104.141 },

  // South
  { name: 'Phuket', description: 'Thailand\'s largest island with stunning beaches and lively nightlife.', imageUrl: provinceImages.Phuket, region: 'South', lat: 7.9519, lng: 98.3381 },
  { name: 'Krabi', description: 'Home to iconic limestone karsts, clear waters, and beautiful islands.', imageUrl: provinceImages.Krabi, region: 'South', lat: 8.085, lng: 98.906 },
  { name: 'Chumphon', description: 'A gateway to the southern islands, with long, quiet beaches.', imageUrl: provinceImages.Chumphon, region: 'South', lat: 10.493, lng: 99.180 },
  { name: 'Nakhon Si Thammarat', description: 'One of the oldest cities in the south, with a rich cultural heritage.', imageUrl: provinceImages['Nakhon Si Thammarat'], region: 'South', lat: 8.437, lng: 99.963 },
  { name: 'Narathiwat', description: 'A culturally rich province in the deep south.', imageUrl: provinceImages.Narathiwat, region: 'South', lat: 6.426, lng: 101.822 },
  { name: 'Pattani', description: 'A province with a strong Malay cultural influence.', imageUrl: provinceImages.Pattani, region: 'South', lat: 6.868, lng: 101.253 },
  { name: 'Phang Nga', description: 'Famous for its stunning bay with hundreds of limestone cliffs and islands.', imageUrl: provinceImages['Phang Nga'], region: 'South', lat: 8.450, lng: 98.525 },
  { name: 'Phatthalung', description: 'A province known for its vast lake and wetland ecosystems.', imageUrl: provinceImages.Phatthalung, region: 'South', lat: 7.618, lng: 100.076 },
  { name: 'Ranong', description: 'Known for its long rainy season and natural hot springs.', imageUrl: provinceImages.Ranong, region: 'South', lat: 9.966, lng: 98.635 },
  { name: 'Satun', description: 'Home to the stunning Tarutao National Marine Park.', imageUrl: provinceImages.Satun, region: 'South', lat: 7.073, lng: 99.789 },
  { name: 'Songkhla', description: 'A major port and commercial hub in the south.', imageUrl: provinceImages.Songkhla, region: 'South', lat: 7.203, lng: 100.595 },
  { name: 'Surat Thani', description: 'The gateway to the popular islands of Koh Samui, Koh Phangan, and Koh Tao.', imageUrl: provinceImages['Surat Thani'], region: 'South', lat: 9.136, lng: 99.333 },
  { name: 'Trang', description: 'Known for its beautiful, unspoiled islands and delicious local food.', imageUrl: provinceImages.Trang, region: 'South', lat: 7.558, lng: 99.613 },
  { name: 'Yala', description: 'The southernmost province, known for its unique blend of cultures.', imageUrl: provinceImages.Yala, region: 'South', lat: 6.541, lng: 101.280 },
  
  // West
  { name: 'Kanchanaburi', description: 'Known for the River Kwai and its World War II history.', imageUrl: provinceImages.Kanchanaburi, region: 'West', lat: 14.021, lng: 99.531 },
  { name: 'Phetchaburi', description: 'A historic city with royal palaces, ancient temples, and beaches.', imageUrl: provinceImages.Phetchaburi, region: 'West', lat: 13.111, lng: 99.945 },
  { name: 'Prachuap Khiri Khan', description: 'Home to the popular resort town of Hua Hin.', imageUrl: provinceImages['Prachuap Khiri Khan'], region: 'West', lat: 11.808, lng: 99.794 },
  { name: 'Ratchaburi', description: 'Famous for its floating markets and beautiful caves.', imageUrl: provinceImages.Ratchaburi, region: 'West', lat: 13.537, lng: 99.818 },
  
  // East
  { name: 'Chachoengsao', description: 'A province with a large and revered Ganesha statue.', imageUrl: provinceImages.Chachoengsao, region: 'East', lat: 13.687, lng: 101.071 },
  { name: 'Chanthaburi', description: 'The "City of Gems," famous for its gem markets and fruit farming.', imageUrl: provinceImages.Chanthaburi, region: 'East', lat: 12.609, lng: 102.103 },
  { name: 'Chonburi', description: 'Home to the famous beach city of Pattaya.', imageUrl: provinceImages.Chonburi, region: 'East', lat: 13.361, lng: 100.985 },
  { name: 'Prachinburi', description: 'A province with abundant natural beauty and ancient ruins.', imageUrl: provinceImages.Prachinburi, region: 'East', lat: 14.050, lng: 101.371 },
  { name: 'Rayong', description: 'Known for its quiet beaches and as the gateway to Koh Samet.', imageUrl: provinceImages.Rayong, region: 'East', lat: 12.671, lng: 101.277 },
  { name: 'Sa Kaeo', description: 'A province bordering Cambodia, known for its cross-border markets.', imageUrl: provinceImages['Sa Kaeo'], region: 'East', lat: 13.818, lng: 102.072 },
  { name: 'Trat', description: 'The easternmost province, and the gateway to Koh Chang.', imageUrl: provinceImages.Trat, region: 'East', lat: 12.243, lng: 102.518 },
];

export const REGION_KEYS = [
  'Central',
  'North',
  'Northeast',
  'South',
  'West',
  'East'
] as const;

export const INTEREST_KEYS = [
  'culture',
  'adventure',
  'beaches',
  'food',
  'nightlife',
  'nature',
  'relaxation',
] as const;

export const FEATURED_ATTRACTIONS: FeaturedAttraction[] = [
  // 77 LANDMARKS MAPPED TO EVERY PROVINCE
  { key: 'grandPalace', name: 'The Grand Palace', province: 'Bangkok', description: 'Official residence of the Kings of Siam.', imageUrl: attractionImages.grandPalace, lat: 13.749, lng: 100.492 },
  { key: 'watMahathat', name: 'Wat Mahathat', province: 'Ayutthaya', description: 'Ancient ruins famous for the Buddha head in tree roots.', imageUrl: attractionImages.watMahathat, lat: 14.357, lng: 100.567 },
  { key: 'watMuang', name: 'Wat Muang', province: 'Ang Thong', description: 'Home to the tallest gold Buddha statue in Thailand.', imageUrl: attractionImages.watMuang, lat: 14.591, lng: 100.418 },
  { key: 'chaiNatBirdPark', name: 'Chai Nat Bird Park', province: 'Chai Nat', description: 'Largest bird park in Asia featuring over 100 species.', imageUrl: attractionImages.chaiNatBirdPark, lat: 15.200, lng: 100.125 },
  { key: 'phraPrangSamYod', name: 'Phra Prang Sam Yod', province: 'Lopburi', description: 'Ancient Khmer three-tower temple, now a monkey sanctuary.', imageUrl: attractionImages.phraPrangSamYod, lat: 14.803, lng: 100.613 },
  { key: 'sarikaFalls', name: 'Sarika Waterfall', province: 'Nakhon Nayok', description: 'Stunning nine-tiered waterfall in a lush forest.', imageUrl: attractionImages.sarikaFalls, lat: 14.316, lng: 101.258 },
  { key: 'phraPathomChedi', name: 'Phra Pathom Chedi', province: 'Nakhon Pathom', description: 'The world\'s tallest stupa, a primary Buddhist landmark.', imageUrl: attractionImages.phraPathomChedi, lat: 13.820, lng: 100.060 },
  { key: 'kohKret', name: 'Koh Kret', province: 'Nonthaburi', description: 'Riverside island famous for Mon pottery and culture.', imageUrl: attractionImages.kohKret, lat: 13.912, lng: 100.485 },
  { key: 'dreamWorld', name: 'Dream World', province: 'Pathum Thani', description: 'Thailand\'s premier family amusement and theme park.', imageUrl: attractionImages.dreamWorld, lat: 14.001, lng: 100.675 },
  { key: 'ancientCity', name: 'The Ancient City', province: 'Samut Prakan', description: 'The world\'s largest outdoor museum with scaled Thai replicas.', imageUrl: attractionImages.ancientCity, lat: 13.538, lng: 100.623 },
  { key: 'watChongLom', name: 'Wat Chong Lom', province: 'Samut Sakhon', description: 'Historic temple offering beautiful views of the river estuary.', imageUrl: attractionImages.watChongLom, lat: 13.541, lng: 100.274 },
  { key: 'maeklongMarket', name: 'Railway Market', province: 'Samut Songkhram', description: 'Unique market where stalls retract for passing trains.', imageUrl: attractionImages.maeklongMarket, lat: 13.411, lng: 100.001 },
  { key: 'watPhraPhutthabat', name: 'Wat Phra Phutthabat', province: 'Saraburi', description: 'Sacred temple housing the "Footprint of the Buddha".', imageUrl: attractionImages.watPhraPhutthabat, lat: 14.718, lng: 100.789 },
  { key: 'bangRachan', name: 'Bang Rachan Memorial', province: 'Sing Buri', description: 'Park honoring historic heroes of the Ayutthaya period.', imageUrl: attractionImages.bangRachan, lat: 14.802, lng: 100.315 },
  { key: 'dragonMuseum', name: 'Dragon Descendants Museum', province: 'Suphan Buri', description: 'Magnificent museum inside a giant dragon statue.', imageUrl: attractionImages.dragonMuseum, lat: 14.478, lng: 100.126 },

  // North
  { key: 'doiInthanon', name: 'Doi Inthanon', province: 'Chiang Mai', description: 'Highest peak in Thailand with twin pagodas.', imageUrl: attractionImages.doiInthanon, lat: 18.588, lng: 98.487 },
  { key: 'whiteTemple', name: 'White Temple', province: 'Chiang Rai', description: 'Contemporary Buddhist art masterpiece.', imageUrl: attractionImages.whiteTemple, lat: 19.824, lng: 99.763 },
  { key: 'kamphaengPhetPark', name: 'Historical Park', province: 'Kamphaeng Phet', description: 'UNESCO ancient ruins and temples.', imageUrl: attractionImages.kamphaengPhetPark, lat: 16.485, lng: 99.522 },
  { key: 'lampangLuang', name: 'Wat Phra That Lampang Luang', province: 'Lampang', description: 'Oldest wooden Lanna-style temple.', imageUrl: attractionImages.lampangLuang, lat: 18.216, lng: 99.387 },
  { key: 'watHariphunchai', name: 'Wat Hariphunchai', province: 'Lamphun', description: 'Legendary golden pagoda from the Mon era.', imageUrl: attractionImages.watHariphunchai, lat: 18.577, lng: 99.009 },
  { key: 'banRakThai', name: 'Ban Rak Thai', province: 'Mae Hong Son', description: 'Scenic Chinese village in the mist.', imageUrl: attractionImages.banRakThai, lat: 19.585, lng: 97.942 },
  { key: 'buengBoraphet', name: 'Bueng Boraphet', province: 'Nakhon Sawan', description: 'Largest freshwater lake in Thailand.', imageUrl: attractionImages.buengBoraphet, lat: 15.712, lng: 100.145 },
  { key: 'watPhumin', name: 'Wat Phumin', province: 'Nan', description: 'Iconic temple with the "Whispering Love" mural.', imageUrl: attractionImages.watPhmin, lat: 18.775, lng: 100.771 },
  { key: 'kwanPhayao', name: 'Kwan Phayao', province: 'Phayao', description: 'Tranquil lake with spectacular sunset views.', imageUrl: attractionImages.kwanPhayao, lat: 19.163, lng: 99.904 },
  { key: 'phaSornKaew', name: 'Wat PhaSornKaew', province: 'Phetchabun', description: 'Stunning mosaic temple in the mountains.', imageUrl: attractionImages.phaSornKaew, lat: 16.788, lng: 101.050 },
  { key: 'watThaLuang', name: 'Wat Tha Luang', province: 'Phichit', description: 'Sacred temple housing Luang Phor Phet.', imageUrl: attractionImages.watThaLuang, lat: 16.442, lng: 100.352 },
  { key: 'phraPhutthaChinnarat', name: 'Wat Mahathat', province: 'Phitsanulok', description: 'Home to the most beautiful Buddha in Thailand.', imageUrl: attractionImages.phraPhutthaChinnarat, lat: 16.822, lng: 100.259 },
  { key: 'phraThatChaeHaeng', name: 'Wat Phra That Chae Haeng', province: 'Phrae', description: 'Historic white pagoda representing the year of the rabbit.', imageUrl: attractionImages.phraThatChaeHaeng, lat: 18.150, lng: 100.130 },
  { key: 'sukhothaiHistoricalPark', name: 'Historical Park', province: 'Sukhothai', description: 'Cradle of Thai civilization UNESCO site.', imageUrl: attractionImages.sukhothaiHistoricalPark, lat: 17.017, lng: 99.704 },
  { key: 'bhumibolDam', name: 'Bhumibol Dam', province: 'Tak', description: 'Massive concrete dam with scenic reservoir views.', imageUrl: attractionImages.bhumibolDam, lat: 17.243, lng: 98.973 },
  { key: 'watThaSung', name: 'Wat Tha Sung', province: 'Uthai Thani', description: 'Dazzling crystal temple interior.', imageUrl: attractionImages.watThaSung, lat: 15.378, lng: 100.031 },
  { key: 'sirikitDam', name: 'Sirikit Dam', province: 'Uttaradit', description: 'Largest earth-filled dam in the kingdom.', imageUrl: attractionImages.sirikitDam, lat: 17.765, lng: 100.562 },

  // Northeast
  { key: 'putthaUtthayan', name: 'Puttha Utthayan', province: 'Amnat Charoen', description: 'Park with a giant golden sitting Buddha.', imageUrl: attractionImages.putthaUtthayan, lat: 15.862, lng: 104.629 },
  { key: 'hinSamWan', name: 'Three Whale Rocks', province: 'Bueng Kan', description: 'Rocks looking like a whale family in the forest.', imageUrl: attractionImages.hinSamWan, lat: 18.355, lng: 103.655 },
  { key: 'phanomRung', name: 'Phanom Rung', province: 'Buriram', description: 'Khmer sanctuary atop an extinct volcano.', imageUrl: attractionImages.phanomRung, lat: 14.532, lng: 102.939 },
  { key: 'paHinNgam', name: 'Pa Hin Ngam', province: 'Chaiyaphum', description: 'Tulip fields and strange rock formations.', imageUrl: attractionImages.paHinNgam, lat: 15.631, lng: 101.392 },
  { key: 'sirindhornMuseum', name: 'Dinosaur Museum', province: 'Kalasin', description: 'Best dinosaur fossils in Southeast Asia.', imageUrl: attractionImages.sirindhornMuseum, lat: 16.694, lng: 103.526 },
  { key: 'kaenNakhon', name: 'Phra Mahathat Kaen Nakhon', province: 'Khon Kaen', description: 'Stunning nine-story pagoda near the lake.', imageUrl: attractionImages.kaenNakhon, lat: 16.425, lng: 102.833 },
  { key: 'phuKradueng', name: 'Phu Kradueng', province: 'Loei', description: 'Popular trekking plateau with sunrise views.', imageUrl: attractionImages.phuKradueng, lat: 16.883, lng: 101.785 },
  { key: 'phraThatNaDun', name: 'Phra That Na Dun', province: 'Maha Sarakham', description: 'Isan Buddhist Park in Dvaravati style.', imageUrl: attractionImages.phraThatNaDun, lat: 15.928, lng: 103.226 },
  { key: 'hoKaeo', name: 'Ho Kaeo Mukdahan', province: 'Mukdahan', description: 'Observation tower overlooking Mekong river.', imageUrl: attractionImages.hoKaeo, lat: 16.545, lng: 104.723 },
  { key: 'phraThatPhanom', name: 'Wat Phra That Phanom', province: 'Nakhon Phanom', description: 'Sacred pagoda housing Buddha\'s breastbone.', imageUrl: attractionImages.phraThatPhanom, lat: 16.943, lng: 104.725 },
  { key: 'phimaiPark', name: 'Phimai Historical Park', province: 'Nakhon Ratchasima (Korat)', description: 'Largest Khmer sanctuary in Thailand.', imageUrl: attractionImages.phimaiPark, lat: 15.221, lng: 102.493 },
  { key: 'shellFossil', name: 'Shell Fossil Museum', province: 'Nong Bua Lamphu', description: 'Prehistoric shell fossil site.', imageUrl: attractionImages.shellFossil, lat: 17.208, lng: 102.441 },
  { key: 'salaKeoku', name: 'Sala Keoku', province: 'Nong Khai', description: 'Surreal concrete sculpture park on Mekong.', imageUrl: attractionImages.salaKeoku, lat: 17.886, lng: 102.781 },
  { key: 'roiEtTower', name: 'Roi Et Tower', province: 'Roi Et', description: 'Iconic observation tower shaped like a "Wot".', imageUrl: attractionImages.roiEtTower, lat: 16.058, lng: 103.655 },
  { key: 'choengChum', name: 'Phra That Choeng Chum', province: 'Sakon Nakhon', description: 'Historic pagoda over sacred footprints.', imageUrl: attractionImages.choengChum, lat: 17.165, lng: 104.148 },
  { key: 'phaMoIDaeng', name: 'Pha Mo I Daeng', province: 'Sisaket', description: 'Scenic cliff at the Cambodian border.', imageUrl: attractionImages.phaMoIDaeng, lat: 14.391, lng: 104.685 },
  { key: 'elephantStudy', name: 'Elephant Study Center', province: 'Surin', description: 'Village dedicated to elephant care and culture.', imageUrl: attractionImages.elephantStudy, lat: 15.281, lng: 103.502 },
  { key: 'samPhanBok', name: 'Sam Phan Bok', province: 'Ubon Ratchathani', description: 'Grand Canyon of Thailand on the Mekong.', imageUrl: attractionImages.samPhanBok, lat: 15.802, lng: 105.353 },
  { key: 'redLotusSea', name: 'Red Lotus Sea', province: 'Udon Thani', description: 'Vast lake filled with millions of pink lotuses.', imageUrl: attractionImages.redLotusSea, lat: 17.183, lng: 103.050 },
  { key: 'phrayaKankak', name: 'Toad Museum', province: 'Yasothon', description: 'Unique museum in a giant toad statue.', imageUrl: attractionImages.phrayaKankak, lat: 15.792, lng: 104.141 },

  // South
  { key: 'bigBuddhaPhuket', name: 'Big Buddha Phuket', province: 'Phuket', description: 'Iconic white marble statue atop a hill.', imageUrl: attractionImages.bigBuddhaPhuket, lat: 7.827, lng: 98.312 },
  { key: 'mayaBay', name: 'Maya Bay', province: 'Krabi', description: 'Crystal blue bay from Hollywood fame.', imageUrl: attractionImages.mayaBay, lat: 7.678, lng: 98.765 },
  { key: 'muKoChumphon', name: 'Marine Park', province: 'Chumphon', description: 'Pristine coral reefs and sandy beaches.', imageUrl: attractionImages.muKoChumphon, lat: 10.455, lng: 99.255 },
  { key: 'watPhraMahathatNS', name: 'Wat Mahathat', province: 'Nakhon Si Thammarat', description: 'Spiritual center of Southern Thailand.', imageUrl: attractionImages.watPhraMahathatNS, lat: 8.411, lng: 99.966 },
  { key: 'watKhaoKong', name: 'Wat Khao Kong', province: 'Narathiwat', description: 'Largest outdoor sitting Buddha in the deep south.', imageUrl: attractionImages.watKhaoKong, lat: 6.402, lng: 101.782 },
  { key: 'centralMosque', name: 'Central Mosque', province: 'Pattani', description: 'Most beautiful mosque in Thailand.', imageUrl: attractionImages.centralMosque, lat: 6.862, lng: 101.252 },
  { key: 'jamesBondIsland', name: 'James Bond Island', province: 'Phang Nga', description: 'Iconic limestone karst in a stunning bay.', imageUrl: attractionImages.jamesBondIsland, lat: 8.274, lng: 98.500 },
  { key: 'thaleNoi', name: 'Thale Noi', province: 'Phatthalung', description: 'Wetland park famous for lotuses and birds.', imageUrl: attractionImages.thaleNoi, lat: 7.755, lng: 100.125 },
  { key: 'raksawarinHotSpring', name: 'Raksawarin Spring', province: 'Ranong', description: 'Natural mineral hot springs for wellness.', imageUrl: attractionImages.raksawarinHotSpring, lat: 9.952, lng: 98.652 },
  { key: 'kohLipe', name: 'Koh Lipe', province: 'Satun', description: 'Maldives of Thailand with clear turquoise water.', imageUrl: attractionImages.kohLipe, lat: 6.488, lng: 99.302 },
  { key: 'samilaBeach', name: 'Samila Beach', province: 'Songkhla', description: 'Famous beach with the Golden Mermaid statue.', imageUrl: attractionImages.samilaBeach, lat: 7.212, lng: 100.602 },
  { key: 'khaoSokPark', name: 'Khao Sok', province: 'Surat Thani', description: 'Ancient rainforest and emerald green lake.', imageUrl: attractionImages.khaoSokPark, lat: 8.912, lng: 98.522 },
  { key: 'emeraldCave', name: 'Emerald Cave', province: 'Trang', description: 'Secret beach hidden inside a limestone cave.', imageUrl: attractionImages.emeraldCave, lat: 7.372, lng: 99.292 },
  { key: 'betongTunnel', name: 'Betong Tunnel', province: 'Yala', description: 'Longest curved traffic tunnel in Thailand.', imageUrl: attractionImages.betongTunnel, lat: 5.772, lng: 101.112 },

  // West & East
  { key: 'bridgeRiverKwai', name: 'River Kwai Bridge', province: 'Kanchanaburi', description: 'Historic WWII Death Railway memorial.', imageUrl: attractionImages.bridgeRiverKwai, lat: 14.041, lng: 99.503 },
  { key: 'khaoWang', name: 'Phra Nakhon Khiri', province: 'Phetchaburi', description: 'White royal palace complex atop a hill.', imageUrl: attractionImages.khaoWang, lat: 13.108, lng: 99.937 },
  { key: 'khaoSamRoiYot', name: 'National Park', province: 'Prachuap Khiri Khan', description: 'Limestone peaks and the Phraya Nakhon cave.', imageUrl: attractionImages.khaoSamRoiYot, lat: 12.185, lng: 99.982 },
  { key: 'floatingMarket', name: 'Damnoen Saduak', province: 'Ratchaburi', description: 'Iconic Thai floating market culture.', imageUrl: attractionImages.floatingMarket, lat: 13.518, lng: 99.957 },
  { key: 'watSothon', name: 'Wat Sothon Wararam', province: 'Chachoengsao', description: 'Magnificent marble temple by the river.', imageUrl: attractionImages.watSothon, lat: 13.674, lng: 101.066 },
  { key: 'cathedralImmaculate', name: 'Gothic Cathedral', province: 'Chanthaburi', description: 'The largest Gothic-style cathedral in Thailand.', imageUrl: attractionImages.cathedralImmaculate, lat: 12.609, lng: 102.119 },
  { key: 'sanctuaryTruth', name: 'Sanctuary of Truth', province: 'Chonburi', description: 'Massive hand-carved wooden temple-castle.', imageUrl: attractionImages.sanctuaryTruth, lat: 12.968, lng: 100.888 },
  { key: 'khaoYaiPrachin', name: 'Khao Yai Gateway', province: 'Prachinburi', description: 'Lush access point to the famous national park.', imageUrl: attractionImages.khaoYaiPrachin, lat: 14.155, lng: 101.405 },
  { key: 'kohSamet', name: 'Koh Samet', province: 'Rayong', description: 'Popular island retreat with fine white sand.', imageUrl: attractionImages.kohSamet, lat: 12.562, lng: 101.448 },
  { key: 'pangSidaPark', name: 'Pang Sida', province: 'Sa Kaeo', description: 'Nature park famous for thousands of butterflies.', imageUrl: attractionImages.pangSidaPark, lat: 13.988, lng: 102.205 },
  { key: 'kohChang', name: 'Koh Chang', province: 'Trat', description: 'Second largest island with rainforests.', imageUrl: attractionImages.kohChang, lat: 12.062, lng: 102.355 },
];
